import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import AppSidebar from "@/components/AppSidebar";
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import AppNavbar from "@/components/AppNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex bg-red-300`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
              <SidebarProvider >
                <AppSidebar />
                <div className="w-full bg-yellow-200 flex flex-col h-full">
                  <div className="flex gap-2 items-center">
                    <SidebarTrigger className="hidden sm:flex flex-none bg-cyan-900" />
                    <AppNavbar />
                  </div>
                  <div className="flex-grow px-4 bg-green-300">
                    {children}
                  </div>
                </div>
              </SidebarProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
